### ISSUE TITLE
What does your dev environment look like?

### ISSUE THREAD

**Issue by sindresorhus** [tenhobi/ama#1]
Editor, terminal, tools, themes, fonts, process, etc.

**Comment by tenhobi** [comment]
An IDE I use is PhpStorm, because it has really awesome hinting and so on. But I use it more like an editor... :smile_cat: Btw. I really like Atom, but now it's not usable for me, at least until they resolve the conflict with keyboards shortcuts and add a little bit better hinting. I like dark themes and because PhpStorm is not so much configurable in terms of desing (Sublime or Atom are on a completely different level) I use default Dracula theme. I also use Sublime Text for simple things where I use very nice Spacegray Eighties theme. 

I use 'git bash' terminal through which I can use bash, which I personally like more than Windows batch. 'Cause I use git I also have some git aliases in .gitconfig file and I did a simple shell to connect it with local git config as I have at https://github.com/dresorhus HoBi/config repository.

For my projects I use tools like npm, bower and gulp. I really love the Sass preprocessor which I use a lot. :heart_eyes:
