### ISSUE TITLE
What's your favorite project on GitHub and why?

### ISSUE THREAD

**Issue by arthurvr** [tenhobi/ama#7]

**Comment by tenhobi** [comment]
This is very interesting and hard question.

I think there are a lot of GitHub project which have really awesome idea and pick only one is not easy. I can only write some useful projects I use right now which make my work easier: Jekyll, Polymer, Sass, jQuery... :)

**Jekyll** because it allows me to create 'pseudo dynamic' webpages and is very easy.
**Polymer** because with it I can make my websites better (more semantic) and I can use local scope for CSS (+ some JS logic) right now.
**Sass** because I just really love :heart_eyes: the abstract way to write CSS like I can do in Sass.
**jQuery** because it makes work with selectors and DOM's changes really simple.

In general I like everything what can meaningfully help someone with work etc. :smile_cat:
